<?php

$base_url = "../";

include "../includes/header.php";
include "../includes/config.php";
include "../includes/sidebar.php";

?>

<main class="main-content">

    <div class="page-title">

        <div>
            <h2>Reports</h2>
            <p>View and generate hostel management reports.</p>
        </div>

    </div>


    <div class="table-container">

        <table>

            <thead>

                <tr>
                    <th>Report ID</th>
                    <th>Report Type</th>
                    <th>Report Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Generated By</th>
                    <th>Action</th>
                </tr>

            </thead>


            <tbody>

                <?php

                $reports = mysqli_query(
                    $conn,
                    "SELECT
                        report.*,
                        staff.staff_fname,
                        staff.staff_lname

                    FROM report

                    JOIN staff
                    ON report.Staff_ID = staff.staff_id

                    ORDER BY report.Report_ID ASC"
                );


                while ($row = mysqli_fetch_assoc($reports)) {

                ?>

                    <tr>

                        <td>
                            <?php echo $row['Report_ID']; ?>
                        </td>


                        <td>
                            <?php echo $row['Report_Type']; ?>
                        </td>


                        <td>
                            <?php echo $row['Report_Name']; ?>
                        </td>


                        <td>
                            <?php echo $row['Start_Date']; ?>
                        </td>


                        <td>
                            <?php echo $row['End_Date']; ?>
                        </td>


                        <td>

                            <?php

                            echo $row['staff_fname']
                                . " "
                                . $row['staff_lname'];

                            ?>

                        </td>


                        <td>

                            <a
                                href="view_report.php?id=<?php echo $row['Report_ID']; ?>"
                                class="edit-btn">

                                View

                            </a>

                        </td>

                    </tr>

                <?php

                }

                ?>

            </tbody>

        </table>

    </div>

</main>


<?php

include "../includes/footer.php";

?>