<?php

$base_url = "../";

include "../includes/auth.php";
include "../includes/config.php";
include "../includes/header.php";
include "../includes/sidebar.php";

?>

<main class="main-content">

    <div class="page-title">

        <div>

            <h2>Reports</h2>

            <p>View and generate hostel management reports.</p>

        </div>

    </div>


    <!-- SEARCH BAR -->

    <div class="search-container">

        <i class="fa-solid fa-magnifying-glass search-icon"></i>

        <input
            type="text"
            id="search"
            placeholder="Search by Report ID, Name or Type..."
        >

        <button
            type="button"
            class="clear-search"
            id="clearSearch">

            <i class="fa-solid fa-xmark"></i>

        </button>

    </div>


    <div class="table-container">

        <table>

            <thead>

                <tr>

                    <th>Report ID</th>
                    <th>Report Type</th>
                    <th>Report Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Generated By</th>
                    <th>Action</th>

                </tr>

            </thead>

            <tbody id="reportTable">

            </tbody>

        </table>

    </div>

</main>

<script src="<?php echo $base_url; ?>javaScript/reports.js"></script>

<?php

include "../includes/footer.php";

?>